# Generated by Django 5.2.4 on 2025-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventTitle', models.CharField(max_length=200)),
                ('EventDate', models.DateField()),
                ('EventTime', models.TimeField()),
                ('Venue', models.TextField()),
                ('Organizer', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=200)),
                ('Organizer2', models.CharField(max_length=200, null=True)),
                ('Contact2', models.CharField(max_length=100, null=True)),
                ('poster_image', models.URLField()),
                ('Description', models.TextField()),
                ('Entry_details', models.TextField(blank=True, null=True)),
                ('HighLights', models.TextField(blank=True, null=True)),
                ('Registration_link', models.URLField(blank=True, null=True)),
                ('Sponsors', models.TextField(blank=True, null=True)),
                ('Instagram_link', models.URLField(blank=True, null=True)),
                ('FaceBook', models.URLField(blank=True, null=True)),
                ('Whatsapp', models.URLField(blank=True, null=True)),
                ('Website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
